language: c++

compiler: g++
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- gcc-7
- g++-7
- cmake
- make

script:
 - gcc -v && g++ -v && cmake --version
 - cd ~/build/natalielutaenko/ToDoListcw/
 - cmake CMakeLists.txt && make && ctest
