language: c++

compiler: g++
addons:
apt:
sources:
- ubuntu-toolchain-r-test
packages:
- gcc-7
- g++-7
- cmake
- make

script:
 - ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
 - ln -s /usr/bin/g++-7 /usr/local/bin/g++
 - export CC=/usr/bin/gcc-7
 - export CXX=/usr/bin/g++-7
 - gcc -v && g++ -v && cmake --version
 - cd ~/build/natalielutaenko/ToDoListcw/
 - cmake CMakeLists.txt && make && ctest
